config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  resources :receptionists
  resources :customers
  resources :doctors
  root 'welcome#index'

end

app/models/doctor.rb
class Doctor < User
  has_many :appointments
  has_many :customers , :through => :appointments
  has_one :doctor_info , foreign_key: 'user_id'

  accepts_nested_attributes_for :doctor_info

  validates :name, presence: true ,length: {maximum: 35 }
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.includes(:doctor_info).all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
    @doctor.build_doctor_info
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.includes(:doctor_info).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, doctor_info_attributes: [:address , :state , :city , :zip, :school ,:years_since_passed ])
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :name %>
  </div>
  <%= f.fields_for :doctor_info do |doctor_info_form| %>
    <div class="field">
      <%= doctor_info_form.label :address %>
      <%= doctor_info_form.text_field :address %>
      <br/>
    </div>
    <div class="field">
      <%= doctor_info_form.label :city %>
      <%= doctor_info_form.text_field :city %>
      <br/>
    </div>
    <div class="field">
      <%= doctor_info_form.label :state %>
      <%= doctor_info_form.text_field :state %>
      <br/>
    </div>
    <div class="field">
      <%= doctor_info_form.label :zip %>
      <%= doctor_info_form.text_field :zip %>
      <br/>
    </div>
    <div class="field">
      <%= doctor_info_form.label :school %>
      <%= doctor_info_form.text_field :school %>
      <br/>
    </div>
    <div class="field">
      <%= doctor_info_form.label :years_since_passed %>
      <%= doctor_info_form.text_field :years_since_passed %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>State</th>
      <th>Years since passed  </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <% doctor.build_doctor_info if doctor.doctor_info.nil? %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.doctor_info.address %></td>
        <td><%= doctor.doctor_info.state %></td>
        <td><%= doctor.doctor_info.years_since_passed %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.doctor_info.address %>
</p>
<p>
  <strong>State:</strong>
  <%= @doctor.doctor_info.state %>
</p>
<p>
  <strong>Zip:</strong>
  <%= @doctor.doctor_info.zip %>
</p>
<p>
  <strong>School:</strong>
  <%= @doctor.doctor_info.school %>
</p>
<p>
  <strong>years since practice :</strong>
  <%= @doctor.doctor_info.years_since_passed %>
</p>
<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>