config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  resources :receptionists
  resources :customers
  resources :doctors
  root 'welcome#index'

end

app/models/receptionist.rb
class Receptionist < User
  
end

app/controllers/receptionists_controller.rb
class ReceptionistsController < ApplicationController
  before_action :set_receptionist, only: [:show, :edit, :update, :destroy]

  # GET /receptionists
  # GET /receptionists.json
  def index
    @receptionists = Receptionist.all
  end

  # GET /receptionists/1
  # GET /receptionists/1.json
  def show
  end

  # GET /receptionists/new
  def new
    @receptionist = Receptionist.new
  end

  # GET /receptionists/1/edit
  def edit
  end

  # POST /receptionists
  # POST /receptionists.json
  def create
    @receptionist = Receptionist.new(receptionist_params)

    respond_to do |format|
      if @receptionist.save
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully created.' }
        format.json { render :show, status: :created, location: @receptionist }
      else
        format.html { render :new }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receptionists/1
  # PATCH/PUT /receptionists/1.json
  def update
    respond_to do |format|
      if @receptionist.update(receptionist_params)
        format.html { redirect_to @receptionist, notice: 'Receptionist was successfully updated.' }
        format.json { render :show, status: :ok, location: @receptionist }
      else
        format.html { render :edit }
        format.json { render json: @receptionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receptionists/1
  # DELETE /receptionists/1.json
  def destroy
    @receptionist.destroy
    respond_to do |format|
      format.html { redirect_to receptionists_url, notice: 'Receptionist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receptionist
      @receptionist = Receptionist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receptionist_params
      params.require(:receptionist).permit(:name)
    end
end

app/helpers/receptionists_helper.rb
module ReceptionistsHelper
end

app/views/receptionists/_form.html.erb
<%= form_for(@receptionist) do |f| %>
  <% if @receptionist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receptionist.errors.count, "error") %> prohibited this receptionist from being saved:</h2>

      <ul>
      <% @receptionist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
     <%= f.label :Name %><br />
     <%= f.text_field :name %>
   </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receptionists/edit.html.erb
<h1>Editing Receptionist</h1>

<%= render 'form' %>

<%= link_to 'Show', @receptionist %> |
<%= link_to 'Back', receptionists_path %>

app/views/receptionists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Receptionists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receptionists.each do |receptionist| %>
      <tr>
          <th><%= receptionist.name%> </th>
        <td><%= link_to 'Show', receptionist %></td>
        <td><%= link_to 'Edit', edit_receptionist_path(receptionist) %></td>
        <td><%= link_to 'Destroy', receptionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receptionist', new_receptionist_path %>

app/views/receptionists/new.html.erb
<h1>New Receptionist</h1>

<%= render 'form' %>

<%= link_to 'Back', receptionists_path %>

app/views/receptionists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @receptionist.name %>
</p>

<%= link_to 'Edit', edit_receptionist_path(@receptionist) %> |
<%= link_to 'Back', receptionists_path %>